/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.dependx

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'gradle.dependx.greeting' plugin.
 */
class GradleDependxPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("gradle.dependx.dependxies")

        // Verify the result
        assertNotNull(project.tasks.findByName("dependxies"))
    }
}
